name: Deploy to AWS Lambda

on:
  push:
    branches: 
      - main  # Runs on pushes to the 'main' branch

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.17'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Create deployment package
      - name: Create deployment package
        run: zip -r ci-cd-gh-action-main.zip . -x ".git/*"

      # Step 5: Deploy to AWS Lambda
      - name: Deploy to AWS Lambda
        uses: appleboy/lambda-action@v0.1.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ap-south-1
          function_name: gh-action-project
          zip_file: ci-cd-gh-action-main.zip
          handler: handler.handler  # This points to handler.js and the handler function inside it
          publish: true
